POST   http://localhost:8000/auth/register
Content-Type: application/json
 
{
    "firstName": "lemma",
    "lastName": "Tariku",
    "email": "lematariu@gmail.com",
    "password":"tarikuuuu"
}


### Create Order
POST http://localhost:8000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OTAxODExYS0xODk4LTQ1OGMtOWE2Yi04NDlmYTNkZjk5YTciLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MTY1NjI4NTMsImV4cCI6MTcxNjY0OTI1M30.OzcE5dxVsZdRYZS0lVapK9cE5OaA_ijKqjqFy3nS938
Content-Type: application/json

{
  "orderItems": [
    {
      "productId": "product-456",
      "quantity": 2
    },
    {
      "productId": "product-789",
      "quantity": 1
    }
  ]
}

