import "./globals.css";
import { DataProvider } from "@app/client/components/admincomponent/globalcontext/DataContext";

import Navigation from "@app/client/components/admincomponent/navigation/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const products = await getManyProducts();
  return (
    <div className="body_admin">
      <Navigation />
      <DataProvider products={products} />

      <div className="body">
        <div>{children}</div>
      </div>
    </div>
  );
}
