import "./globals.css";
import { DataProvider } from "@app/client/components/admincomponent/globalcontext/DataContext";


import Navigation from "@app/client/components/admincomponent/navigation/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    
  
      <div className="body_admin">
        <Navigation/>
    
        <DataProvider>
          <div className="body">
            <div>
              {children}
            </div>
            
          </div>
        </DataProvider>
    
     
      </div>
  );
}
